# Generated by Django 3.1.5 on 2021-01-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date'], 'verbose_name': 'Makale', 'verbose_name_plural': 'Makaleler'},
        ),
    ]
