# Generated by Django 3.1.5 on 2021-01-13 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210113_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 1, 13, 19, 6, 16, 905223, tzinfo=utc), upload_to='article/', verbose_name='Kapak Resmi'),
            preserve_default=False,
        ),
    ]
