# Generated by Django 3.1.5 on 2021-01-13 19:21

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=article.models.upload_article_image, verbose_name='Kapak Resmi'),
        ),
    ]
